name: Continuous integration

on:
  push:
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12, 14, 16, 18, 20, 22 ,24 ]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install packages
      run: bun install

    - name: Continuous integration
      run: bun run debug-test

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 12, 14, 16, 18, 20, 22, 24 ]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Checkout Git Source
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install Dependencies
      run: bun install

    - name: Continuous integration
      run: bun run debug-test
